### ISSUE TITLE
reduce redundancy in job scripts

### ISSUE THREAD

**Issue by koadman** [koadman/proxigenomics#42] opened 2015-10-27 20:46 UTC
currently there are a large number of SGE & PBS job scripts. These scripts contain a lot of code redundancy as they also support local pipeline execution.

Now that we are no longer stuck with the clunky UTS HPC cluster this can all be streamlined to use DRMAA and the job scripts eliminated. 3rd party users wishing to run the pipeline could simply start a GVL instance in amazon EC2 or NeCTAR.

**Comment by cerebis** [comment] 2015-11-13 00:14
The intention it to reimplement runtime support using DRMAA. This might be way of [gridmap](https://github.com/pygridtools/gridmap) or just [python-drmaa](https://github.com/pygridtools/drmaa-python)

**Comment by cerebis** [comment] 2015-11-13 00:20
Duplicate of #18

**Closed by cerebis** 2015-11-13 00:20 UTC
